version: '3.8'

services:
  suna-sandbox:
    build:
      context: .
      dockerfile: Dockerfile
    image: local-suna-sandbox:latest
    container_name: suna-sandbox-${PROJECT_ID:-default}
    hostname: suna-sandbox
    
    # 端口映射
    ports:
      - "${VNC_PORT:-15901}:5901"          # VNC服务器
      - "${NOVNC_PORT:-16080}:6080"        # noVNC Web界面
      - "${BROWSER_API_PORT:-17788}:7788"  # 浏览器API
      - "${FILE_SERVER_PORT:-18080}:8080"  # 文件服务器
    
    # 环境变量
    environment:
      - DISPLAY=:99
      - RESOLUTION=${RESOLUTION:-1024x768x24}
      - RESOLUTION_WIDTH=${RESOLUTION_WIDTH:-1024}
      - RESOLUTION_HEIGHT=${RESOLUTION_HEIGHT:-768}
      - VNC_PASSWORD=${VNC_PASSWORD:-vncpassword}
      - WORKSPACE_PATH=/workspace
      - PYTHONUNBUFFERED=1
      - CHROME_PERSISTENT_SESSION=true
      - ANONYMIZED_TELEMETRY=false
      - TZ=${TZ:-Asia/Shanghai}
    
    # 数据卷
    volumes:
      - suna-workspace-${PROJECT_ID:-default}:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    
    # 共享内存大小
    shm_size: 2g
    
    # 特权和安全选项
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
    
    # 资源限制
    deploy:
      resources:
        limits:
          cpus: '${CPU_LIMIT:-2}'
          memory: ${MEMORY_LIMIT:-4G}
        reservations:
          cpus: '0.5'
          memory: 1G
    
    # 重启策略
    restart: unless-stopped
    
    # 健康检查
    healthcheck:
      test: [
        "CMD-SHELL",
        "nc -z localhost 5901 && nc -z localhost 6080 && nc -z localhost 8080 || exit 1"
      ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # 网络
    networks:
      - suna-network
    
    # 标签
    labels:
      - "suna.service=sandbox"
      - "suna.project_id=${PROJECT_ID:-default}"
      - "suna.version=1.0.0"
      - "traefik.enable=false"

# 数据卷定义
volumes:
  suna-workspace-${PROJECT_ID:-default}:
    driver: local
    labels:
      - "suna.workspace=true"
      - "suna.project_id=${PROJECT_ID:-default}"

# 网络定义
networks:
  suna-network:
    driver: bridge
    name: suna-sandbox-network
    labels:
      - "suna.network=true"